#
# Copyright © 2013 Sven Ruppert (sven.ruppert@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

workspace:
  base: /drone/src
  path: workdir

#services:
#  docker:
#    image: docker:18.04.0-ce-dind
#    environment:
##    privileged: true

volumes:
  - /var/run/docker.sock:/var/run/docker.sock

pipeline:
  build:
    image: ${JDK_VERSION}
    pull: true
    commands:
      - mkdir /root/.m2
#      - cp /drone/src/rapidpm-dependencies/_data/nexus/settings.xml /root/.m2/settings.xml
      - mvn clean
      - mvn dependency:go-offline
      - mvn install -Pvaadin-install-nodejs
#      - mvn test

#  deploy:
#    image: ${JDK_VERSION}
#    pull: true
#    commands:
#      - mkdir /root/.m2
#      - cp /drone/src/rapidpm-dependencies/_data/nexus/settings.xml /root/.m2/settings.xml
#      - mvn clean
#      - mvn deploy
#    when:
#        matrix:
#          JDK_VERSION: svenruppert/maven-3.5-jdk-10
#        branches:
#          include: develop, release/*
#          exclude: feature/*


matrix:
  JDK_VERSION:
    - svenruppert/maven-3.6.1-adopt:1.8.212-04
#    - svenruppert/maven-3.5-jdk-08
#    - svenruppert/maven-3.5-jdk-openjdk-09
#    - svenruppert/maven-3.5-jdk-openjdk-10
#    - svenruppert/maven-3.5-jdk-openjdk-11
#    - svenruppert/maven-3.5-jdk-openjdk-shenandoah-08
#    - svenruppert/maven-3.5-jdk-openjdk-shenandoah-09
#    - svenruppert/maven-3.5-jdk-openjdk-shenandoah-10
#    - svenruppert/maven-3.5-jdk-graalvm-ce-01
#    - svenruppert/maven-3.5-jdk-oracle-08
#    - svenruppert/maven-3.5-jdk-oracle-10
#    - svenruppert/maven-3.5-jdk-oracle-11
#    - svenruppert/maven-3.5-jdk-zulu-08
#    - svenruppert/maven-3.5-jdk-zulu-09
#    - svenruppert/maven-3.5-jdk-zulu-10
#    - svenruppert/maven-3.5-jdk-ibm-08
#  - maven:3.5-ibmjava-8-alpine
#  - maven:3.5-ibmjava-9-alpine
